name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Flutter analyze
        run: flutter analyze
